"""Initial migration

Revision ID: fa596dc83a94
Revises: 
Create Date: 2026-03-21 10:15:22.034687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa596dc83a94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_logs_module'), 'crawl_logs', ['module'], unique=False)
    op.create_index(op.f('ix_crawl_logs_started_at'), 'crawl_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_crawl_logs_status'), 'crawl_logs', ['status'], unique=False)
    op.create_table('earnings_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('fiscal_quarter', sa.String(length=10), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('revenue_yoy_growth', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('revenue_estimate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revenue_surprise_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('eps_estimate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps_surprise_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('gross_margin_change', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('guidance', sa.String(length=20), nullable=True),
    sa.Column('guidance_revenue_low', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('guidance_revenue_high', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('guidance_eps_low', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('guidance_eps_high', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('is_first_public_report', sa.Boolean(), nullable=True),
    sa.Column('days_since_ipo', sa.Integer(), nullable=True),
    sa.Column('vs_s1_trajectory', sa.String(length=20), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_earnings_first', 'earnings_reports', ['is_first_public_report'], unique=False)
    op.create_index('idx_earnings_ticker_date', 'earnings_reports', ['ticker', 'report_date'], unique=True)
    op.create_table('institutional_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('shares_held', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shares_changed', sa.Integer(), nullable=True),
    sa.Column('pct_change', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('portfolio_weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holdings_ticker_inst', 'institutional_holdings', ['ticker', 'institution_name'], unique=False)
    op.create_index(op.f('ix_institutional_holdings_ticker'), 'institutional_holdings', ['ticker'], unique=False)
    op.create_table('ipo_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('price_range_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_range_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shares_offered', sa.Integer(), nullable=True),
    sa.Column('deal_size_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lead_underwriter', sa.String(length=255), nullable=True),
    sa.Column('s1_filing_url', sa.Text(), nullable=True),
    sa.Column('prospectus_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ipo_cik_date', 'ipo_events', ['cik', 'expected_date'], unique=True)
    op.create_index(op.f('ix_ipo_events_cik'), 'ipo_events', ['cik'], unique=False)
    op.create_index(op.f('ix_ipo_events_expected_date'), 'ipo_events', ['expected_date'], unique=False)
    op.create_index(op.f('ix_ipo_events_status'), 'ipo_events', ['status'], unique=False)
    op.create_index(op.f('ix_ipo_events_ticker'), 'ipo_events', ['ticker'], unique=False)
    op.create_table('lockup_info',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('ipo_date', sa.Date(), nullable=False),
    sa.Column('lockup_days', sa.Integer(), nullable=False),
    sa.Column('lockup_expiry_date', sa.Date(), nullable=False),
    sa.Column('shares_locked', sa.Integer(), nullable=True),
    sa.Column('locked_holders', sa.Text(), nullable=True),
    sa.Column('early_release_provisions', sa.Boolean(), nullable=True),
    sa.Column('early_release_conditions', sa.Text(), nullable=True),
    sa.Column('total_shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('float_after_ipo', sa.Integer(), nullable=True),
    sa.Column('float_after_lockup', sa.Integer(), nullable=True),
    sa.Column('supply_impact_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('parsed_from_s1', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_lockup_info_lockup_expiry_date'), 'lockup_info', ['lockup_expiry_date'], unique=False)
    op.create_index(op.f('ix_lockup_info_status'), 'lockup_info', ['status'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_ticker_url', 'news_items', ['ticker', 'url'], unique=True)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_items_ticker'), 'news_items', ['ticker'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_social_ticker_platform', 'social_posts', ['ticker', 'platform'], unique=False)
    op.create_index(op.f('ix_social_posts_created_at'), 'social_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_posts_ticker'), 'social_posts', ['ticker'], unique=False)
    op.create_table('stock_bars',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('vwap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_index('idx_bars_ticker_date', 'stock_bars', ['ticker', 'date'], unique=False)
    op.create_table('s1_filings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('revenue_yoy_growth', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('use_of_proceeds', sa.Text(), nullable=True),
    sa.Column('risk_factors_summary', sa.Text(), nullable=True),
    sa.Column('customer_concentration', sa.Text(), nullable=True),
    sa.Column('lockup_days', sa.Integer(), nullable=True),
    sa.Column('lockup_expiry_date', sa.Date(), nullable=True),
    sa.Column('shares_locked', sa.Integer(), nullable=True),
    sa.Column('locked_holders', sa.Text(), nullable=True),
    sa.Column('early_release_provisions', sa.Boolean(), nullable=True),
    sa.Column('total_shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('float_after_ipo', sa.Integer(), nullable=True),
    sa.Column('s1_url', sa.Text(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cik'], ['ipo_events.cik'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_s1_cik_date', 's1_filings', ['cik', 'filed_date'], unique=True)
    op.create_index(op.f('ix_s1_filings_cik'), 's1_filings', ['cik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_s1_filings_cik'), table_name='s1_filings')
    op.drop_index('idx_s1_cik_date', table_name='s1_filings')
    op.drop_table('s1_filings')
    op.drop_index('idx_bars_ticker_date', table_name='stock_bars')
    op.drop_table('stock_bars')
    op.drop_index(op.f('ix_social_posts_ticker'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_created_at'), table_name='social_posts')
    op.drop_index('idx_social_ticker_platform', table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_news_items_ticker'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index('idx_news_ticker_url', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_lockup_info_status'), table_name='lockup_info')
    op.drop_index(op.f('ix_lockup_info_lockup_expiry_date'), table_name='lockup_info')
    op.drop_table('lockup_info')
    op.drop_index(op.f('ix_ipo_events_ticker'), table_name='ipo_events')
    op.drop_index(op.f('ix_ipo_events_status'), table_name='ipo_events')
    op.drop_index(op.f('ix_ipo_events_expected_date'), table_name='ipo_events')
    op.drop_index(op.f('ix_ipo_events_cik'), table_name='ipo_events')
    op.drop_index('idx_ipo_cik_date', table_name='ipo_events')
    op.drop_table('ipo_events')
    op.drop_index(op.f('ix_institutional_holdings_ticker'), table_name='institutional_holdings')
    op.drop_index('idx_holdings_ticker_inst', table_name='institutional_holdings')
    op.drop_table('institutional_holdings')
    op.drop_index('idx_earnings_ticker_date', table_name='earnings_reports')
    op.drop_index('idx_earnings_first', table_name='earnings_reports')
    op.drop_table('earnings_reports')
    op.drop_index(op.f('ix_crawl_logs_status'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_started_at'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_module'), table_name='crawl_logs')
    op.drop_table('crawl_logs')
    # ### end Alembic commands ###
